set global grepcmd 'rg -Hn'
# set global indentwidth 0
set global indentwidth 2
set global tabstop 2

set global disabled_hooks '.*-(highlight|insert)'

set global autoinfo command|onkey

colorscheme plain

add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces
add-highlighter global/ regex \h+$ 0:Error
add-highlighter global/ wrap -word -indent
add-highlighter global/ column '%opt{autowrap_column}' default,red

# set-option -add global ui_options terminal_status_on_top=true
# set-option -add global ui_options terminal_enable_mouse=false
# set-option -add global ui_options terminal_assistant=none
# set-option -add global ui_options terminal_padding_char=/ # More fancy examples: ▚ ╳ ╱ ┼
# set-option -add global ui_options terminal_padding_fill=yes
# set-option -add global ui_options terminal_set_title=no

# Previous versions config rules
set-option -add global ui_options ncurses_assistant=none
set-option -add global ui_options ncurses_enable_mouse=false
set-option -add global ui_options ncurses_status_on_top=true

hook global WinCreate ^[^*]+$ %{ add-highlighter window/ number-lines }

hook global BufOpenFile .* %{editorconfig-load}
hook global BufNewFile .* %{editorconfig-load}

set-face global CurSearch +u
set-face global CurWord +b

map global normal '#' :comment-line<ret>
map global normal '<a-#>' :comment-block<ret>

# CTAGS: universal-ctags
# set-option global ctagscmd "uctags -R --fields=+S"
# set-option global readtagscmd "ureadtags"
# map global normal <a-.> :ctags-search<ret>
#
# MAKE
# define-command recompile %{
#   write-all
#   make
# }
# map global normal <c-m> ':make<ret>'
# map global normal <c-r> ':recompile<ret>'
# map global normal <c-n> ':make-next-error<ret>'

map global normal <space> , -docstring 'leader'
map global normal , <space>

source "%val{config}/lsp.kak"
