# Kakoune
# https://github.com/mawww/kakoune

set-option global grepcmd "rg --vimgrep --hidden"
define-command find -menu -params 1 -shell-script-candidates %{fdfind --ignore-file "$kak_opt_ignored_files"} %{edit %arg{1}}

set-option global indentwidth 4
set-option global tabstop 4

set-option global autocomplete prompt
set-option global autoinfo command|onkey
set-option global disabled_hooks ".*-(highlight|insert)"

colorscheme plain

add-highlighter global/ show-matching -previous
add-highlighter global/ show-whitespaces
add-highlighter global/ regex \h+$ 0:Error
add-highlighter global/ wrap -word -indent
add-highlighter global/ column '%opt{autowrap_column}' default,red

set-option -add global ui_options terminal_status_on_top=true
set-option -add global ui_options terminal_enable_mouse=false
set-option -add global ui_options terminal_assistant=none
# set-option -add global ui_options terminal_padding_char=/ # More fancy examples: ▚ ╳ ╱ ┼
# set-option -add global ui_options terminal_padding_fill=yes
set-option -add global ui_options terminal_set_title=no

# Previous versions config rules
# set-option -add global ui_options ncurses_assistant=none
# set-option -add global ui_options ncurses_enable_mouse=false
# set-option -add global ui_options ncurses_status_on_top=true

hook global WinCreate ^[^*]+$ %{add-highlighter window/ number-lines -separator " "}

hook global BufOpenFile .* %{editorconfig-load}
hook global BufNewFile .* %{editorconfig-load}

set-face global CurSearch +u
set-face global CurWord +b

map global normal "#" :comment-line<ret>
map global normal "<a-#>" :comment-block<ret>

# map global normal <space> , -docstring 'leader'
# map global normal , <space>
map -docstring "enter user mode" global user <space> :

hook global WinSetOption filetype=(?!makefile).* %{
  map global insert <tab> "<a-;><a-gt>"
  map global insert <s-tab> "<a-;><a-lt>"
}

# source "%val{config}/ctags.kak"
# source "%val{config}/make.kak"
source "%val{config}/lsp.kak"
# source "%val{config}/tree-sitter.kak"
source "%val{config}/kcr.kak"
